### ISSUE TITLE
I want to meet and talk with you.

### ISSUE THREAD

**Issue by natan3** [t32k/feedback#1]
# 自己紹介と、あなたに会いたい理由

初めまして、@natan3(twitter)と申します。
## 自己紹介

大学（２回目の）４年情報系専攻の学生です。現在、某会社からエンジニアとして内定を頂いております。
## あなたに会いたい理由

こちらを拝読させていただきました。
http://t32k.me/mol/log/c32k/

PHP, cakePHP, CSS, JS, HTML, MySQLをある程度学習し、現在はアルバイトの一環でrailsとreactJSについて学んでおります。将来は海外の企業で働きたいと思っており、OB訪問よりもカジュアルな感じで詳しいお話を伺えればと思いました。

よろしければtwitterなどでご連絡いただけると嬉しいです。

**Comment by t32k** [comment]
@natan3 

> 将来は海外の企業で働きたいと思っており

であれば、自分は失敗した身でありますし、私が経験したことは上記のブログで述べましたので、残念ながら特にアドバイスできることもないかと思います。

記事でも述べましたように、クリエイターの海外留学を支援しているFrogというエージェントさんに相談してみると良いかもしれません（相談だけなら無料なので）。僕もバンクーバーでの滞在先の手配をお願いしました。年に何回か東京で説明会も開催してるようなので参加してみてください。
- [メンバー | Frog](http://frogagent.com/team/)

> ４年情報系専攻の学生

若くてうらやましいです。がんばっていろいろ挑戦してみてください。

**Comment by natan3** [comment]
ご回答ありがとうございます。

> 特にアドバイスできることもないかと思います。
> 残念です。

Frogについていろいろ調べてみようと思います。
